version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - 3310:3306/tcp
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: always
    container_name: nextcloud-app
    hostname: "nextcloud-app"
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    ports:
      - 9099:443/tcp
    volumes:
      - nextcloud:/var/www/html:ro
      - ./proxy/certs:/etc/ssl/nginx:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud: