version: "3.7"

services:

  proxy:
    image: nginx
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 9099:443/tcp
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      #- ./proxy/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./proxy/certs:/etc/ssl/nginx:ro
      #- /etc/localtime:/etc/localtime:ro
      #- /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

#    image: jwilder/nginx-proxy:alpine
#    #    labels:
#    #      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
#    container_name: nextcloud-proxy
#    networks:
#      - nextcloud_network
#    ports:
#      #- 80:80
#      #- 443:443
#    volumes:
#      - ./proxy/conf.d:/etc/nginx/conf.d:rw
#      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
#      #- ./proxy/html:/usr/share/nginx/html:rw
#      - ./proxy/certs:/etc/nginx/certs:ro
#      - /etc/localtime:/etc/localtime:ro
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      #- letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      #- ./app/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      #- ./app/config:/var/www/html/config
      #- ./app/custom_apps:/var/www/html/custom_apps
      #- ./app/data:/var/www/html/data
      #- ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=nextcloud.YOUR-DOMAIN
      - LETSENCRYPT_HOST=nextcloud.YOUR-DOMAIN
      - LETSENCRYPT_EMAIL=YOUR-EMAIL
    restart: unless-stopped

      # letsencrypt:
      # image: jrcs/letsencrypt-nginx-proxy-companion
      # container_name: nextcloud-letsencrypt
      # depends_on:
      # - proxy
      # networks:
      # - nextcloud_network
      # volumes:
      # - ./proxy/certs:/etc/nginx/certs:rw
      # - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      # - ./proxy/html:/usr/share/nginx/html:rw
      # - /etc/localtime:/etc/localtime:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    # restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network: