version: '3.7'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - 3310:3306/tcp
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    hostname: "nextcloud-app"
    container_name: nextcloud-app
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - NEXTCLOUD_TABLE_PREFIX=
      - NEXTCLOUD_UPDATE=1
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.example.com
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    networks:
      - proxy-tier
      - default
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      #- 80:80
      #- 443:443
      - 9099:443
    volumes:
      - ./proxy/certs:/etc/ssl/nginx:ro
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:

networks:
  proxy-tier: